const fs = require('fs');
const path = 'app/mocks/index.ts';
let content = fs.readFileSync(path, 'utf8');

// Replace mockProjects
content = content.replace(
  /export const mockProjects: ProjectProgress\[\] = \[([\s\S]*?)\]/,
  `export const mockProjects: ProjectProgress[] = [
  { id: 'p1', name: 'Nova Praça Central', progress: 45, color: 'bg-blue-500' },
  { id: 'p2', name: 'Manutenção da Frota', progress: 77, color: 'bg-violet-500' },
  { id: 'p3', name: 'Revisão de Licitações da Saúde', progress: 45, color: 'bg-amber-400' },
  { id: 'p4', name: 'Portal do Cidadão', progress: 45, color: 'bg-pink-500' },
  { id: 'p5', name: 'Sistema de Alvarás', progress: 62, color: 'bg-cyan-500' },
  { id: 'p6', name: 'Iluminação Pública', progress: 30, color: 'bg-indigo-500' },
]`
);

const newTasks = `export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Fiscalizar obra da Nova Praça Central',
    priority: 'alta',
    status: 'a-fazer',
    project: 'Nova Praça Central',
    team: 'Engenharia',
    dueDate: '25 Mai',
    projectProgress: 45,
    progress: 0,
    assignees: [PEOPLE.costa, PEOPLE.ana],
    description: 'Fiscalizar o andamento da obra, verificando materiais e medição.',
    startDate: '10/05/2026',
    type: 'Fiscalização',
    complexity: 'Alta',
    category: 'Obras',
    program: 'Mais Praças',
    stars: 2,
    subtasks: [
      { id: 'st1-1', title: 'Verificar alicerces', completed: false, assignee: PEOPLE.costa, dueDate: '12/05/26' },
      { id: 'st1-2', title: 'Medir concretagem', completed: false, assignee: PEOPLE.costa, dueDate: '18/05/26' },
      { id: 'st1-3', title: 'Conferir notas fiscais', completed: false, assignee: PEOPLE.ana, dueDate: '20/05/26' },
      { id: 'st1-4', title: 'Aprovar relatório final', completed: false, assignee: PEOPLE.ana, dueDate: '23/05/26' },
    ],
    auditLog: [
      { id: 'al1-1', icon: 'i-heroicons-clipboard-document-list', message: 'Tarefa criada', user: 'Fernanda Souza', timestamp: '10/05/2026 às 09:30' },
    ],
  },
  {
    id: 't2',
    title: 'Cotar peças para ônibus',
    priority: 'media',
    status: 'em-andamento',
    project: 'Manutenção da Frota',
    team: 'Logística',
    dueDate: '16 Jun',
    projectProgress: 77,
    progress: 50,
    assignees: [PEOPLE.costa],
    description: 'Fazer cotação de peças para os ônibus escolares da frota municipal.',
    startDate: '01/05/2026',
    type: 'Aquisição',
    complexity: 'Média',
    category: 'Logística',
    program: 'Frota Renovada',
    stars: 1,
    subtasks: [
      { id: 'st2-1', title: 'Listar peças necessárias', completed: true, assignee: PEOPLE.costa, dueDate: '05/05/26' },
      { id: 'st2-2', title: 'Contatar 3 fornecedores', completed: true, assignee: PEOPLE.costa, dueDate: '10/05/26' },
      { id: 'st2-3', title: 'Receber orçamentos', completed: false, assignee: PEOPLE.costa, dueDate: '15/05/26' },
      { id: 'st2-4', title: 'Enviar para aprovação', completed: false, assignee: PEOPLE.costa, dueDate: '25/05/26' },
    ],
    auditLog: [
      { id: 'al2-1', icon: 'i-heroicons-clipboard-document-list', message: 'Tarefa criada', user: 'Fernanda Souza', timestamp: '01/05/2026 às 08:45' },
    ],
  },
  {
    id: 't3',
    title: 'Revisar contrato Y de medicamentos',
    priority: 'alta',
    status: 'validar',
    project: 'Revisão de Licitações da Saúde',
    team: 'Jurídico',
    dueDate: '25 Mai',
    projectProgress: 45,
    progress: 100,
    assignees: [PEOPLE.costa],
    description: 'Revisar as cláusulas do contrato Y para compra de medicamentos.',
    startDate: '05/05/2026',
    type: 'Revisão',
    complexity: 'Alta',
    category: 'Jurídico',
    program: 'Saúde Mais',
    stars: 3,
    subtasks: [
      { id: 'st3-1', title: 'Ler contrato base', completed: true, assignee: PEOPLE.costa, dueDate: '10/05/26' },
      { id: 'st3-2', title: 'Verificar multas', completed: true, assignee: PEOPLE.costa, dueDate: '15/05/26' },
    ],
    auditLog: [
      { id: 'al3-1', icon: 'i-heroicons-clipboard-document-list', message: 'Tarefa criada', user: 'Ana Carol', timestamp: '05/05/2026 às 10:00' },
    ],
  },
  {
    id: 't4',
    title: 'Atualizar portal com novos serviços',
    priority: 'media',
    status: 'em-revisao',
    project: 'Portal do Cidadão',
    team: 'TI',
    dueDate: '16 Jun',
    projectProgress: 45,
    progress: 90,
    assignees: [PEOPLE.costa, PEOPLE.beatriz],
    description: 'Inserir serviços de emissão de IPTU e certidões no portal.',
    startDate: '20/04/2026',
    type: 'Desenvolvimento',
    complexity: 'Média',
    category: 'TI',
    program: 'Prefeitura Digital',
    stars: 2,
    subtasks: [
      { id: 'st4-1', title: 'Criar página IPTU', completed: true, assignee: PEOPLE.costa, dueDate: '28/04/26' },
      { id: 'st4-2', title: 'Criar página Certidões', completed: true, assignee: PEOPLE.costa, dueDate: '05/05/26' },
      { id: 'st4-3', title: 'Revisar textos', completed: true, assignee: PEOPLE.beatriz, dueDate: '10/05/26' },
      { id: 'st4-4', title: 'Testar links', completed: false, assignee: PEOPLE.beatriz, dueDate: '20/05/26' },
    ],
    auditLog: [],
  },
  {
    id: 't5',
    title: 'Auditar processos atrasados de alvarás',
    priority: 'alta',
    status: 'atrasado',
    project: 'Sistema de Alvarás',
    team: 'Fiscalização',
    dueDate: '08 Mai',
    projectProgress: 62,
    progress: 25,
    note: 'Atrasada há 3 semanas',
    assignees: [PEOPLE.costa],
    description: 'Verificar por que os alvarás da zona sul estão parados.',
    startDate: '20/04/2026',
    type: 'Auditoria',
    complexity: 'Alta',
    category: 'Fiscalização',
    program: 'Empreende Cidade',
    stars: 0,
    subtasks: [
      { id: 'st5-1', title: 'Levantar processos pendentes', completed: true, assignee: PEOPLE.costa, dueDate: '23/04/26' },
      { id: 'st5-2', title: 'Notificar auditores', completed: false, assignee: PEOPLE.costa, dueDate: '28/04/26' },
    ],
    auditLog: [],
  },
  {
    id: 't6',
    title: 'Aprovar projeto de novos postes',
    priority: 'baixa',
    status: 'concluido',
    project: 'Iluminação Pública',
    team: 'Engenharia',
    dueDate: '12 Mai',
    projectProgress: 30,
    progress: 100,
    assignees: [PEOPLE.costa],
    description: 'Aprovar o projeto de expansão da iluminação no bairro Centro.',
    startDate: '01/05/2026',
    type: 'Aprovação',
    complexity: 'Baixa',
    category: 'Infraestrutura',
    program: 'Luz para Todos',
    stars: 1,
    subtasks: [
      { id: 'st6-1', title: 'Ler projeto', completed: true, assignee: PEOPLE.costa, dueDate: '02/05/26' },
      { id: 'st6-2', title: 'Assinar termo', completed: true, assignee: PEOPLE.costa, dueDate: '05/05/26' },
    ],
    auditLog: [],
  },
  {
    id: 't7',
    title: 'Reunião com empreiteira',
    priority: 'media',
    status: 'pausado',
    project: 'Nova Praça Central',
    team: 'Gestão',
    dueDate: '20 Jun',
    projectProgress: 45,
    progress: 10,
    assignees: [PEOPLE.costa],
    description: 'Alinhamento mensal sobre os atrasos na obra.',
    startDate: '01/06/2026',
    type: 'Reunião',
    complexity: 'Média',
    category: 'Gestão',
    program: 'Mais Praças',
    stars: 0,
    subtasks: [
      { id: 'st7-1', title: 'Agendar sala', completed: false, assignee: PEOPLE.costa, dueDate: '10/06/26' },
    ],
    auditLog: [],
  },
  {
    id: 't8',
    title: 'Comprar novas vans',
    priority: 'alta',
    status: 'cancelado',
    project: 'Manutenção da Frota',
    team: 'Aquisições',
    dueDate: '15 Jul',
    projectProgress: 77,
    progress: 0,
    assignees: [PEOPLE.costa],
    description: 'Processo cancelado por falta de verba no orçamento atual.',
    startDate: '01/07/2026',
    type: 'Aquisição',
    complexity: 'Alta',
    category: 'Frota',
    program: 'Frota Renovada',
    stars: 0,
    subtasks: [],
    auditLog: [],
  },
  {
    id: 't9',
    title: 'Verificar denúncias na licitação',
    priority: 'alta',
    status: 'a-fazer',
    project: 'Revisão de Licitações da Saúde',
    team: 'Ouvidoria',
    dueDate: '30 Ago',
    projectProgress: 45,
    progress: 0,
    assignees: [PEOPLE.costa],
    description: 'Analisar denúncias recebidas via canal oficial sobre o pregão 04/2026.',
    startDate: '01/08/2026',
    type: 'Auditoria',
    complexity: 'Alta',
    category: 'Controle Interno',
    program: 'Saúde Mais',
    stars: 3,
    subtasks: [
      { id: 'st9-1', title: 'Ler denúncia', completed: false, assignee: PEOPLE.costa, dueDate: '05/08/26' },
      { id: 'st9-2', title: 'Solicitar documentos', completed: false, assignee: PEOPLE.costa, dueDate: '10/08/26' },
    ],
    auditLog: [],
  },
  {
    id: 't10',
    title: 'Responder ouvidoria do Portal',
    priority: 'media',
    status: 'em-andamento',
    project: 'Portal do Cidadão',
    team: 'Atendimento',
    dueDate: '10 Ago',
    projectProgress: 45,
    progress: 50,
    assignees: [PEOPLE.costa],
    description: 'Responder chamados abertos pelos cidadãos sobre erro no IPTU.',
    startDate: '25/07/2026',
    type: 'Atendimento',
    complexity: 'Baixa',
    category: 'Suporte',
    program: 'Prefeitura Digital',
    stars: 1,
    subtasks: [
      { id: 'st10-1', title: 'Triagem de chamados', completed: true, assignee: PEOPLE.costa, dueDate: '30/07/26' },
      { id: 'st10-2', title: 'Responder usuários', completed: false, assignee: PEOPLE.costa, dueDate: '05/08/26' },
    ],
    auditLog: [],
  },
  {
    id: 't11',
    title: 'Treinamento de analistas de alvará',
    priority: 'media',
    status: 'validar',
    project: 'Sistema de Alvarás',
    team: 'RH',
    dueDate: '20 Jul',
    projectProgress: 62,
    progress: 100,
    assignees: [PEOPLE.costa, PEOPLE.daniel],
    description: 'Treinar novos servidores no sistema recém implantado.',
    startDate: '10/07/2026',
    type: 'Treinamento',
    complexity: 'Média',
    category: 'RH',
    program: 'Servidor Capacitado',
    stars: 2,
    subtasks: [
      { id: 'st11-1', title: 'Preparar material', completed: true, assignee: PEOPLE.costa, dueDate: '12/07/26' },
      { id: 'st11-2', title: 'Reservar laboratório', completed: true, assignee: PEOPLE.costa, dueDate: '14/07/26' },
      { id: 'st11-3', title: 'Ministrar aula turma A', completed: true, assignee: PEOPLE.daniel, dueDate: '18/07/26' },
      { id: 'st11-4', title: 'Ministrar aula turma B', completed: true, assignee: PEOPLE.daniel, dueDate: '19/07/26' },
    ],
    auditLog: [],
  },
  {
    id: 't12',
    title: 'Mapear ruas sem iluminação',
    priority: 'alta',
    status: 'em-revisao',
    project: 'Iluminação Pública',
    team: 'Engenharia',
    dueDate: '15 Ago',
    projectProgress: 30,
    progress: 90,
    assignees: [PEOPLE.costa],
    description: 'Mapeamento noturno das vias do bairro Zona Norte.',
    startDate: '01/08/2026',
    type: 'Mapeamento',
    complexity: 'Alta',
    category: 'Infraestrutura',
    program: 'Luz para Todos',
    stars: 1,
    subtasks: [
      { id: 'st12-1', title: 'Ronda noturna', completed: true, assignee: PEOPLE.costa, dueDate: '05/08/26' },
      { id: 'st12-2', title: 'Gerar relatório', completed: false, assignee: PEOPLE.costa, dueDate: '10/08/26' },
    ],
    auditLog: [],
  },
  {
    id: 't13',
    title: 'Medição final do canteiro',
    priority: 'alta',
    status: 'atrasado',
    project: 'Nova Praça Central',
    team: 'Fiscalização',
    dueDate: '10 Jul',
    projectProgress: 45,
    progress: 80,
    note: 'Atrasada há 2 semanas',
    assignees: [PEOPLE.costa],
    description: 'Fazer a medição para liberar a última parcela do pagamento.',
    startDate: '01/07/2026',
    type: 'Fiscalização',
    complexity: 'Alta',
    category: 'Obras',
    program: 'Mais Praças',
    stars: 0,
    subtasks: [
      { id: 'st13-1', title: 'Visita técnica', completed: true, assignee: PEOPLE.costa, dueDate: '05/07/26' },
      { id: 'st13-2', title: 'Assinar medição', completed: false, assignee: PEOPLE.costa, dueDate: '08/07/26' },
    ],
    auditLog: [],
  },
  {
    id: 't14',
    title: 'Trocar pneus da frota leve',
    priority: 'media',
    status: 'concluido',
    project: 'Manutenção da Frota',
    team: 'Mecânica',
    dueDate: '20 Jun',
    projectProgress: 77,
    progress: 100,
    assignees: [PEOPLE.costa],
    description: 'Substituição preventiva dos pneus das viaturas.',
    startDate: '10/06/2026',
    type: 'Manutenção',
    complexity: 'Baixa',
    category: 'Frota',
    program: 'Frota Renovada',
    stars: 0,
    subtasks: [
      { id: 'st14-1', title: 'Comprar pneus', completed: true, assignee: PEOPLE.costa, dueDate: '15/06/26' },
      { id: 'st14-2', title: 'Agendar troca', completed: true, assignee: PEOPLE.costa, dueDate: '18/06/26' },
    ],
    auditLog: [],
  },
  {
    id: 't15',
    title: 'Publicar edital do posto de saúde',
    priority: 'alta',
    status: 'pausado',
    project: 'Revisão de Licitações da Saúde',
    team: 'Licitações',
    dueDate: '30 Set',
    projectProgress: 45,
    progress: 10,
    assignees: [PEOPLE.costa],
    description: 'Publicar edital para construção do novo posto de saúde, aguardando dotação orçamentária.',
    startDate: '01/09/2026',
    type: 'Publicação',
    complexity: 'Média',
    category: 'Jurídico',
    program: 'Saúde Mais',
    stars: 0,
    subtasks: [
      { id: 'st15-1', title: 'Revisar edital', completed: false, assignee: PEOPLE.costa, dueDate: '15/09/26' },
    ],
    auditLog: [],
  },
  /* Tarefas pessoais (sem projeto, equipe ou progresso) */
  {
    id: 'tp1',
    title: 'Agendar férias',
    priority: 'alta',
    status: 'a-fazer',
    dueDate: '15 Jul',
    personal: true,
    assignees: [],
  },
  {
    id: 'tp2',
    title: 'Organizar documentos da mesa',
    priority: 'media',
    status: 'a-fazer',
    dueDate: '10 Jun',
    personal: true,
    assignees: [],
  },
  {
    id: 'tp3',
    title: 'Curso de licitações e contratos',
    priority: 'media',
    status: 'em-andamento',
    dueDate: '05 Jun',
    personal: true,
    assignees: [],
  },
  {
    id: 'tp4',
    title: 'Solicitar crachá novo',
    priority: 'baixa',
    status: 'a-fazer',
    dueDate: '30 Jun',
    personal: true,
    assignees: [],
  },
  {
    id: 'tp5',
    title: 'Entregar atestado médico no RH',
    priority: 'baixa',
    status: 'concluido',
    dueDate: '18 Jun',
    personal: true,
    assignees: [],
  },
  {
    id: 'tp6',
    title: 'Assinar folha de ponto mensal',
    priority: 'baixa',
    status: 'a-fazer',
    dueDate: '22 Mai',
    personal: true,
    assignees: [],
  },
]`;

// Replace mockTasks
content = content.replace(
  /export const mockTasks: Task\[\] = \[([\s\S]*?)\]\n\n\/\* -------------------------------------------------------------- Equipes \(modal\) \*\//,
  newTasks + '\n\n/* -------------------------------------------------------------- Equipes (modal) */'
);

fs.writeFileSync(path, content, 'utf8');
console.log('Done!');
